import React from 'react';
import { Button } from '../../lib';
import ExamplesHeader from '../common/header';
import ExampleList from '../common/list';
import {
  MAJOR, MINOR, PLAIN, SUCCESS, INFO, DANGER, WARNING, CUSTOM,
  RECT, ROUNDED_RECT, CAPSULE, SQUARE, ROUNDED_SQUARE, CIRCLE, DIAMOND,
  LG,
  TOP, TOP_LEFT, TOP_RIGHT, RIGHT, BOTTOM, BOTTOM_LEFT, BOTTOM_RIGHT, LEFT,
} from '../../lib/common/constant';
import { StyledButtonShape } from './styles/ButtonShape';

const ButtonShape = () => {
  return (
    <>
      <StyledButtonShape className='section-item'>
        <ExamplesHeader>
          button shape - 按钮形状
        </ExamplesHeader>
        <ExampleList inline className='button-list'>
          <ExampleList.Item>
            <Button
              skin={MAJOR}
              size={LG}
            >
              {RECT} - 矩形
            </Button>
          </ExampleList.Item>
          <ExampleList.Item>
            <Button
              skin={MINOR}
              size={LG}
              shape={ROUNDED_RECT}
            >
              {ROUNDED_RECT} - 圆角矩形
            </Button>
          </ExampleList.Item>
          <ExampleList.Item>
            <Button
              skin={PLAIN}
              size={LG}
              shape={CAPSULE}
            >
              {CAPSULE} - 胶囊状
            </Button>
          </ExampleList.Item>
          <ExampleList.Item>
            <Button
              skin={SUCCESS}
              size={LG}
              shape={SQUARE}
            >
              {SQUARE} - 正方形
            </Button>
          </ExampleList.Item>
          <ExampleList.Item>
            <Button
              skin={INFO}
              size={LG}
              shape={ROUNDED_SQUARE}
            >
              {ROUNDED_SQUARE} - 圆角正方形
            </Button>
          </ExampleList.Item>
          <ExampleList.Item>
            <Button
              skin={DANGER}
              size={LG}
              shape={CIRCLE}
            >
              {CIRCLE} - 圆形
            </Button>
          </ExampleList.Item>
          <ExampleList.Item>
            <Button
              skin={WARNING}
              size={LG}
              shape={DIAMOND}
            >
              {DIAMOND} - 菱形
            </Button>
          </ExampleList.Item>
          <ExampleList.Item>
            <Button
              skin={CUSTOM}
              size={LG}
              shape={CAPSULE}
            >
              {CAPSULE} - 胶囊状
            </Button>
          </ExampleList.Item>
        </ExampleList>
        <div className='tip-warning'>
          <ol>
            <li>
              when the shape='{SQUARE}' | '{ROUNDED_SQUARE}'  | '{CIRCLE}', extra content is not displayed
              -
              当shape是{SQUARE}、{ROUNDED_SQUARE}或{CIRCLE}时，多余内容不会显示；
            </li>
          </ol>
        </div>
      </StyledButtonShape>
      <StyledButtonShape className='section-item'>
        <ExamplesHeader>
          button shape border radius position - 按钮形状圆角位置
        </ExamplesHeader>
        <ExampleList inline className='button-list'>
          <ExampleList.Item>
            <Button
              skin={MAJOR}
              shape={ROUNDED_RECT}
              size={LG}
              borderRadiusPosition={TOP}
            >
              {TOP}
            </Button>
          </ExampleList.Item>
          <ExampleList.Item>
            <Button
              skin={MINOR}
              size={LG}
              shape={ROUNDED_RECT}
              borderRadiusPosition={TOP_LEFT}
            >
              {TOP_LEFT}
            </Button>
          </ExampleList.Item>
          <ExampleList.Item>
            <Button
              skin={PLAIN}
              size={LG}
              shape={ROUNDED_RECT}
              borderRadiusPosition={TOP_RIGHT}
            >
              {TOP_RIGHT}
            </Button>
          </ExampleList.Item>
          <ExampleList.Item>
            <Button
              skin={SUCCESS}
              size={LG}
              shape={ROUNDED_RECT}
              borderRadiusPosition={RIGHT}
            >
              {RIGHT}
            </Button>
          </ExampleList.Item>
          <ExampleList.Item>
            <Button
              skin={INFO}
              size={LG}
              shape={ROUNDED_RECT}
              borderRadiusPosition={BOTTOM}
            >
              {BOTTOM}
            </Button>
          </ExampleList.Item>
          <ExampleList.Item>
            <Button
              skin={DANGER}
              size={LG}
              shape={ROUNDED_RECT}
              borderRadiusPosition={BOTTOM_LEFT}
            >
              {BOTTOM_LEFT}
            </Button>
          </ExampleList.Item>
          <ExampleList.Item>
            <Button
              skin={WARNING}
              size={LG}
              shape={ROUNDED_RECT}
              borderRadiusPosition={BOTTOM_RIGHT}
            >
              {BOTTOM_RIGHT}
            </Button>
          </ExampleList.Item>
          <ExampleList.Item>
            <Button
              skin={CUSTOM}
              size={LG}
              shape={ROUNDED_RECT}
              borderRadiusPosition={LEFT}
            >
              {LEFT}
            </Button>
          </ExampleList.Item>
        </ExampleList>
        <ExampleList inline className='button-list'>
          <ExampleList.Item>
            <Button
              skin={MAJOR}
              shape={CAPSULE}
              size={LG}
              borderRadiusPosition={TOP}
            >
              {TOP}
            </Button>
          </ExampleList.Item>
          <ExampleList.Item>
            <Button
              skin={MINOR}
              size={LG}
              shape={CAPSULE}
              borderRadiusPosition={TOP_LEFT}
            >
              {TOP_LEFT}
            </Button>
          </ExampleList.Item>
          <ExampleList.Item>
            <Button
              skin={PLAIN}
              size={LG}
              shape={CAPSULE}
              borderRadiusPosition={TOP_RIGHT}
            >
              {TOP_RIGHT}
            </Button>
          </ExampleList.Item>
          <ExampleList.Item>
            <Button
              skin={SUCCESS}
              size={LG}
              shape={CAPSULE}
              borderRadiusPosition={RIGHT}
            >
              {RIGHT}
            </Button>
          </ExampleList.Item>
          <ExampleList.Item>
            <Button
              skin={INFO}
              size={LG}
              shape={CAPSULE}
              borderRadiusPosition={BOTTOM}
            >
              {BOTTOM}
            </Button>
          </ExampleList.Item>
          <ExampleList.Item>
            <Button
              skin={DANGER}
              size={LG}
              shape={CAPSULE}
              borderRadiusPosition={BOTTOM_LEFT}
            >
              {BOTTOM_LEFT}
            </Button>
          </ExampleList.Item>
          <ExampleList.Item>
            <Button
              skin={WARNING}
              size={LG}
              shape={CAPSULE}
              borderRadiusPosition={BOTTOM_RIGHT}
            >
              {BOTTOM_RIGHT}
            </Button>
          </ExampleList.Item>
          <ExampleList.Item>
            <Button
              skin={CUSTOM}
              size={LG}
              shape={CAPSULE}
              borderRadiusPosition={LEFT}
            >
              {LEFT}
            </Button>
          </ExampleList.Item>
        </ExampleList>
        <ExampleList inline className='button-list'>
          <ExampleList.Item>
            <Button
              skin={MAJOR}
              shape={ROUNDED_SQUARE}
              size={LG}
              borderRadiusPosition={TOP}
            >
              {TOP}
            </Button>
          </ExampleList.Item>
          <ExampleList.Item>
            <Button
              skin={MINOR}
              size={LG}
              shape={ROUNDED_SQUARE}
              borderRadiusPosition={TOP_LEFT}
            >
              {TOP_LEFT}
            </Button>
          </ExampleList.Item>
          <ExampleList.Item>
            <Button
              skin={PLAIN}
              size={LG}
              shape={ROUNDED_SQUARE}
              borderRadiusPosition={TOP_RIGHT}
            >
              {TOP_RIGHT}
            </Button>
          </ExampleList.Item>
          <ExampleList.Item>
            <Button
              skin={ROUNDED_SQUARE}
              size={LG}
              shape={CAPSULE}
              borderRadiusPosition={RIGHT}
            >
              {RIGHT}
            </Button>
          </ExampleList.Item>
          <ExampleList.Item>
            <Button
              skin={INFO}
              size={LG}
              shape={ROUNDED_SQUARE}
              borderRadiusPosition={BOTTOM}
            >
              {BOTTOM}
            </Button>
          </ExampleList.Item>
          <ExampleList.Item>
            <Button
              skin={DANGER}
              size={LG}
              shape={ROUNDED_SQUARE}
              borderRadiusPosition={BOTTOM_LEFT}
            >
              {BOTTOM_LEFT}
            </Button>
          </ExampleList.Item>
          <ExampleList.Item>
            <Button
              skin={WARNING}
              size={LG}
              shape={ROUNDED_SQUARE}
              borderRadiusPosition={BOTTOM_RIGHT}
            >
              {BOTTOM_RIGHT}
            </Button>
          </ExampleList.Item>
          <ExampleList.Item>
            <Button
              skin={CUSTOM}
              size={LG}
              shape={ROUNDED_SQUARE}
              borderRadiusPosition={LEFT}
            >
              {LEFT}
            </Button>
          </ExampleList.Item>
        </ExampleList>
        <ExampleList inline className='button-list'>
          <ExampleList.Item>
            <Button
              skin={MAJOR}
              shape={CIRCLE}
              size={LG}
              borderRadiusPosition={TOP}
            >
              {TOP}
            </Button>
          </ExampleList.Item>
          <ExampleList.Item>
            <Button
              skin={MINOR}
              size={LG}
              shape={CIRCLE}
              borderRadiusPosition={TOP_LEFT}
            >
              {TOP_LEFT}
            </Button>
          </ExampleList.Item>
          <ExampleList.Item>
            <Button
              skin={PLAIN}
              size={LG}
              shape={CIRCLE}
              borderRadiusPosition={TOP_RIGHT}
            >
              {TOP_RIGHT}
            </Button>
          </ExampleList.Item>
          <ExampleList.Item>
            <Button
              skin={SUCCESS}
              size={LG}
              shape={CIRCLE}
              borderRadiusPosition={RIGHT}
            >
              {RIGHT}
            </Button>
          </ExampleList.Item>
          <ExampleList.Item>
            <Button
              skin={INFO}
              size={LG}
              shape={CIRCLE}
              borderRadiusPosition={BOTTOM}
            >
              {BOTTOM}
            </Button>
          </ExampleList.Item>
          <ExampleList.Item>
            <Button
              skin={DANGER}
              size={LG}
              shape={CIRCLE}
              borderRadiusPosition={BOTTOM_LEFT}
            >
              {BOTTOM_LEFT}
            </Button>
          </ExampleList.Item>
          <ExampleList.Item>
            <Button
              skin={WARNING}
              size={LG}
              shape={CIRCLE}
              borderRadiusPosition={BOTTOM_RIGHT}
            >
              {BOTTOM_RIGHT}
            </Button>
          </ExampleList.Item>
          <ExampleList.Item>
            <Button
              skin={CUSTOM}
              size={LG}
              shape={CIRCLE}
              borderRadiusPosition={LEFT}
            >
              {LEFT}
            </Button>
          </ExampleList.Item>
        </ExampleList>
        <div className='tip-warning'>
          <ol>
            <li>
              only if the value of shape='{ROUNDED_RECT}' | '{CAPSULE}' | '{ROUNDED_SQUARE}' | '{CIRCLE}', it will work
              -
              只有shape的值为{ROUNDED_RECT}, {CAPSULE}, {ROUNDED_SQUARE}或{CIRCLE}时，才生效；
            </li>
          </ol>
        </div>
      </StyledButtonShape>
    </>
  );
};

export default ButtonShape;
